name: CI/CD
on: 
  push: {}
  workflow_dispatch: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Docker login
        run: docker login ghcr.io -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Build
        run: |
          docker build \
            -t ghcr.io/$GITHUB_REPOSITORY/$(basename $PWD)/image:$(git rev-parse --short HEAD) \
            -t ghcr.io/$GITHUB_REPOSITORY/$(basename $PWD)/image:latest .
      - name: Push
        run: |
          docker push ghcr.io/$GITHUB_REPOSITORY/$(basename $PWD)/image:$(git rev-parse --short HEAD)
          docker push ghcr.io/$GITHUB_REPOSITORY/$(basename $PWD)/image:latest
      - name: Deploy D2C
        run: wget -qO- ${{ secrets.D2C_DEPLOY_WEBHOOK }}
